"use client";

import { useState } from "react";
import { ExternalLink, TrendingUp, TrendingDown, Minus, MessageSquare, Sparkles } from "lucide-react";
import { NewsItem } from "@/db/schema";
import { ChatModal } from "./ChatModal";

interface NewsCardProps {
  item: NewsItem;
}

function formatSourceName(source: string | null) {
  if (!source || source === "hackernews") return "HN";
  if (source === "newsapi") return "NewsAPI";
  return source.replace(/^\w/, (c) => c.toUpperCase()).replace(/-/g, " ");
}

function extractPublisher(url: string): string | null {
  try {
    const hostname = new URL(url).hostname.replace(/^www\./, "");
    // e.g. "techcrunch.com" → "TechCrunch", "theverge.com" → "The Verge"
    const name = hostname.split(".")[0];
    return name.charAt(0).toUpperCase() + name.slice(1);
  } catch {
    return null;
  }
}

export function NewsCard({ item }: NewsCardProps) {
  const [showChat, setShowChat] = useState(false);
  const sentiment = item.sentimentScore ?? 5;
  const publisher = item.source === "newsapi" ? extractPublisher(item.url) : null;

  const getGlowClass = () => {
    if (sentiment >= 8) return "glow-green border-green-500/50";
    if (sentiment <= 3) return "glow-red border-red-500/50";
    return "border-zinc-700";
  };

  const getSentimentIcon = () => {
    if (sentiment >= 7) return <TrendingUp className="w-4 h-4 text-green-500" />;
    if (sentiment <= 3) return <TrendingDown className="w-4 h-4 text-red-500" />;
    return <Minus className="w-4 h-4 text-zinc-500" />;
  };

  const getSentimentColor = () => {
    if (sentiment >= 7) return "text-green-500";
    if (sentiment <= 3) return "text-red-500";
    return "text-zinc-400";
  };

  const formatDate = (date: Date | null) => {
    if (!date) return "Unknown";
    return new Intl.DateTimeFormat("en-US", {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    }).format(new Date(date));
  };

  return (
    <>
      <article
        className={`
          bg-zinc-900/80 backdrop-blur border rounded-lg overflow-hidden
          transition-all duration-300 hover:bg-zinc-800/80
          ${getGlowClass()}
        `}
      >
        {/* Article Image */}
        {item.imageUrl && (
          <div className="relative w-full h-48 bg-zinc-800">
            <img
              src={item.imageUrl}
              alt=""
              className="w-full h-full object-cover"
              loading="lazy"
              onError={(e) => {
                (e.target as HTMLImageElement).parentElement!.style.display = "none";
              }}
            />
          </div>
        )}

        <div className="p-5">
        {/* Header */}
        <div className="flex items-start justify-between gap-4 mb-3">
          <h2 className="font-semibold text-zinc-100 leading-tight">
            {item.title}
          </h2>
          <div className="flex items-center gap-2 flex-shrink-0">
            <button
              onClick={() => setShowChat(true)}
              className="p-2 rounded-md bg-zinc-800 hover:bg-green-600 transition-colors group"
              title="Chat with this article"
            >
              <MessageSquare className="w-4 h-4 text-zinc-400 group-hover:text-white" />
            </button>
            <a
              href={item.url}
              target="_blank"
              rel="noopener noreferrer"
              className="p-2 rounded-md bg-zinc-800 hover:bg-zinc-700 transition-colors"
            >
              <ExternalLink className="w-4 h-4 text-zinc-400" />
            </a>
          </div>
        </div>

        {/* Summary */}
        <p className="text-zinc-400 text-sm mb-4 leading-relaxed">
          {item.summary}
        </p>

        {/* Footer */}
        <div className="flex items-center justify-between text-xs font-mono-display">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="px-2 py-1 rounded bg-zinc-800 text-zinc-300">
              {item.category ?? "Other"}
            </span>
            {item.aiGenerated && (
              <span className="flex items-center gap-1 px-2 py-1 rounded bg-purple-500/15 text-purple-400" title="Summary generated by AI from title only">
                <Sparkles className="w-3 h-3" />
                <span>AI</span>
              </span>
            )}
            {publisher && (
              <span className="px-2 py-1 rounded bg-zinc-800/60 text-zinc-500">
                {publisher}
              </span>
            )}
            <div className={`flex items-center gap-1 ${getSentimentColor()}`}>
              {getSentimentIcon()}
              <span>{sentiment}/10</span>
            </div>
          </div>
          <time className="text-zinc-500">
            {formatDate(item.publishedAt)}
          </time>
        </div>
        </div>
      </article>

      {/* Chat Modal */}
      {showChat && <ChatModal article={item} onClose={() => setShowChat(false)} />}
    </>
  );
}
